# Generated by Django 3.2.9 on 2022-01-08 22:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventoryManager', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductReplenishment',
            new_name='TotalProductReplenishment',
        ),
    ]
