# Generated by Django 3.2.9 on 2022-01-02 02:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventoryManager', '0004_productcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcount',
            name='author',
        ),
        migrations.RemoveField(
            model_name='productcount',
            name='data',
        ),
        migrations.AddField(
            model_name='productcount',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productcount',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventoryManager.product'),
        ),
        migrations.CreateModel(
            name='TotalProductCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('author', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('data', models.ManyToManyField(to='inventoryManager.ProductCount')),
            ],
        ),
    ]
