# Generated by Django 3.2.9 on 2022-01-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatefile',
            name='image',
        ),
        migrations.AddField(
            model_name='privatefile',
            name='file',
            field=models.FileField(default='no-img.jpeg', upload_to='private'),
        ),
    ]
